import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;

public class ReportGenerator {

    public static void main(String[] args) {
        try {
            Document document = new Document();

            PdfWriter.getInstance(document, new FileOutputStream("Report.pdf"));

            document.open();

            // Title
            Font titleFont = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD);
            Paragraph title = new Paragraph("AUTOMATED REPORT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(new Paragraph("\n"));

            // Content
            Font contentFont = new Font(Font.FontFamily.TIMES_ROMAN, 12);
            Paragraph content = new Paragraph(
                    "This is a sample report generated using Java.\n" +
                    "You can add dynamic content, images, and formatting.\n",
                    contentFont
            );
            document.add(content);

            document.add(new Paragraph("\n"));

            // Add Image
            Image image = Image.getInstance("sample.jpg"); // put your image path
            image.scaleToFit(400, 300);
            image.setAlignment(Element.ALIGN_CENTER);
            document.add(image);

            document.add(new Paragraph("\n"));

            // Footer
            Paragraph footer = new Paragraph("Generated by Java Report System");
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();

            System.out.println("PDF Created Successfully!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}